In [1]:
import cnn

n_densities = 32
n_slopes = 32
n_folds = 1
batch_size = 1

dataset = cnn.ChirpTextureDataModule(
    n_densities=n_densities,
    n_slopes=n_slopes,
    n_folds=n_folds,
    batch_size=batch_size)

dataset.setup()

CQT kernels created, time used = 0.0463 seconds
CQT kernels created, time used = 0.0275 seconds
CQT kernels created, time used = 0.0229 seconds

In [3]:
dataset.df

      density_idx  slope_idx   density     slope  fold
0               0          0  0.030303 -0.939394     0
1               0          1  0.030303 -0.878788     0
2               0          2  0.030303 -0.818182     0
3               0          3  0.030303 -0.757576     0
4               0          4  0.030303 -0.696970     0
...           ...        ...       ...       ...   ...
1019           31         27  0.969697  0.696970     0
1020           31         28  0.969697  0.757576     0
1021           31         29  0.969697  0.818182     0
1022           31         30  0.969697  0.878788     0
1023           31         31  0.969697  0.939394     0

[1024 rows x 5 columns]